############################## developer options #############3
publishDir = "docs"

######################## default configuration ####################
#baseURL = "http://adhiyagya.org"
baseURL = "https://himanshuguptagit.github.io/adhiyagya-website2/"
title = "Adhiyagya"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.css]]
link = "plugins/gridder/jquery.gridder.min.css"
[[params.plugins.css]]
link = "plugins/gridder/gridder.css"
[[params.plugins.css]]
link = "plugins/vendor/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/vendor/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/vendor/jquery.timepicker.css"
[[params.plugins.css]]
link = "plugins/vendor/bootstrap-datepicker.css"
[[params.plugins.css]]
link = "plugins/vendor/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/vendor/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/vendor/popper.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

[[params.plugins.js]]
link = "plugins/gridder/jquery.gridder.min.js"
[[params.plugins.js]]
link = "plugins/vendor/jquery-migrate-3.0.1.min.js"
[[params.plugins.js]]
link = "plugins/vendor/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/vendor/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/vendor/jquery.stellar.min.js"
[[params.plugins.js]]
link = "plugins/vendor/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/vendor/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/vendor/scrollax.min.js"
[[params.plugins.js]]
link = "plugins/vendor/jquery.timepicker.min.js"
[[params.plugins.js]]
link = "plugins/vendor/bootstrap-datepicker.js"
[[params.plugins.js]]
link = "plugins/vendor/aos.js"


[[params.plugins.js]]
link = "plugins/custom/main.js"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Causes"
URL = "cause"
weight = 2

[[menu.main]]
name = "Events"
URL = "event"
weight = 3

[[menu.main]]
name = "Team"
URL = "members"
weight = 4

  
[[menu.main]]
name = "blog"
URL = "blog"
weight = 5
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 6


# footer menu

[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo2 = "images/logo-board.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "201, Harsh Bhawan 64-65, New Delhi – 110019"
mobile = "+91-858 786 1167"
email = "adhiyagya.ngo@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
#copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
